1,6d
/^_start[	 |]/d
/^clear[	 |]/d
/^end[	 |]/d
/^env[	 |]/d
/^excep_norm[	 |]/d
/^excep_tab[	 |]/d
/^err_str[	 |]/d
/^excep_msg[	 |]/d
/^excep_proc[	 |]/d
/^excep_int[	 |]/d
/^excep_stack[	 |]/d
/^l_into_x[	 |]/d
/^track[	 |]/d
/^getc[	 |]/d
/^getchar[	 |]/d
/^host_int[	 |]/d
/^introutine[	 |]/d
/^key_int[	 |]/d
/^main [	 |]/d
/^max[	 |]/d
/^min[	 |]/d
/^newline[	 |]/d
/^msvid_int[	 |]/d
/^msvid_pcb[	 |]/d
/^out_int[	 |]/d
/^pcb[	 |]/d
/^putc[	 |]/d
/^string[	 |]/d
/^stack_pcb[	 |]/d
/^clippt[	 |]/d
/^curse[	 |]/d
/^getanum[	 |]/d
/^nlcount[	 |]/d
/^numbers[	 |]/d
/^pt[	 |]/d
/^rect[	 |]/d
/^lsys_start[	 |]/d
/^pvtab[	 |]/d
/^lenvtab[	 |]/d
/^rvtab[	 |]/d
/^sendnchar[	 |]/d
